# -*- coding: utf-8 -*-
"""Cleaning_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqqNh3FoY0Ps0k03Hau0YrHB-VE8V9jo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# File paths
cleaned_data_file = '/content/drive/MyDrive/Frality/Data_Clean/cleaned_data.csv'

# Load cleaned data
df = pd.read_csv(cleaned_data_file)

# Summary statistics
summary_stats = df.describe()
print("Summary Statistics:")
print(summary_stats)

# Correlation matrix (to see relationships between numeric variables)
correlation_matrix = df.corr()
print("Correlation Matrix:")
print(correlation_matrix)

# Visualize correlations using a heatmap
plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.savefig('/content/drive/MyDrive/Frality/Result/EDA/correlation_heatmap.png')
plt.show()

# Scatter plot of Grip Strength vs Age, colored by Frailty
plt.figure(figsize=(8,6))
sns.scatterplot(x='Age', y='Grip Strength', hue='Frailty', data=df, palette='coolwarm')
plt.title('Grip Strength vs Age (Colored by Frailty)')
plt.savefig('/content/drive/MyDrive/Frality/Result/EDA/grip_vs_age_frailty.png')
plt.show()

# Box plot of Grip Strength vs Frailty
plt.figure(figsize=(8,6))
sns.boxplot(x='Frailty', y='Grip Strength', data=df, palette='coolwarm')
plt.title('Boxplot of Grip Strength by Frailty')
plt.savefig('/content/drive/MyDrive/Frality/Result/EDA/grip_strength_frailty_boxplot.png')
plt.show()