# -*- coding: utf-8 -*-
"""Cleaning_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqqNh3FoY0Ps0k03Hau0YrHB-VE8V9jo
"""

import pandas as pd

# File paths
raw_data_file = '/content/drive/MyDrive/Frality/Data_Raw/raw_data.csv'
cleaned_data_file = '/content/drive/MyDrive/Frality/Data_Clean/cleaned_data.csv'

# Load raw data
df = pd.read_csv(raw_data_file)

#data cleaning
# Drop rows with missing values
df.dropna(inplace=True)

# Convert height, weight, and grip strength to floats if necessary
df['Height'] = df['Height'].astype(float)
df['Weight'] = df['Weight'].astype(float)
df['Age'] = df['Age'].astype(int)
df['Grip Strength'] = df['Grip Strength'].astype(float)

# Convert frailty (Y/N) to binary (1 for Yes, 0 for No)
df['Frailty'] = df['Frailty'].map({'Y': 1, 'N': 0})

# Save the cleaned data
df.to_csv(cleaned_data_file, index=False)

print(f"Data cleaning complete. Cleaned data saved to {cleaned_data_file}.")

